## Switches
# Operand A (Lower 6 switches: SW0 - SW5)
set_property PACKAGE_PIN V17 [get_ports {sw_A[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_A[0]}]
set_property PACKAGE_PIN V16 [get_ports {sw_A[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_A[1]}]
set_property PACKAGE_PIN W16 [get_ports {sw_A[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_A[2]}]
set_property PACKAGE_PIN W17 [get_ports {sw_A[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_A[3]}]
set_property PACKAGE_PIN W15 [get_ports {sw_A[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_A[4]}]
set_property PACKAGE_PIN V15 [get_ports {sw_A[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_A[5]}]

# Operand B (Next 6 switches: SW6 - SW11)
set_property PACKAGE_PIN W14 [get_ports {sw_B[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_B[0]}]
set_property PACKAGE_PIN W13 [get_ports {sw_B[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_B[1]}]
set_property PACKAGE_PIN V2 [get_ports {sw_B[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_B[2]}]
set_property PACKAGE_PIN T3 [get_ports {sw_B[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_B[3]}]
set_property PACKAGE_PIN T2 [get_ports {sw_B[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_B[4]}]
set_property PACKAGE_PIN R3 [get_ports {sw_B[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_B[5]}]

# ALU Control (Top 4 switches: SW12 - SW15) [cite: 53]
set_property PACKAGE_PIN W2 [get_ports {sw_ctrl[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_ctrl[0]}]
set_property PACKAGE_PIN U1 [get_ports {sw_ctrl[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_ctrl[1]}]
set_property PACKAGE_PIN T1 [get_ports {sw_ctrl[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_ctrl[2]}]
set_property PACKAGE_PIN R2 [get_ports {sw_ctrl[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_ctrl[3]}]


## LEDs
# ALU Result (Lower 15 LEDs: LED0 - LED14) 
set_property PACKAGE_PIN U16 [get_ports {led[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN E19 [get_ports {led[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property PACKAGE_PIN U19 [get_ports {led[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property PACKAGE_PIN V19 [get_ports {led[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property PACKAGE_PIN W18 [get_ports {led[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property PACKAGE_PIN U15 [get_ports {led[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property PACKAGE_PIN U14 [get_ports {led[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property PACKAGE_PIN V14 [get_ports {led[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property PACKAGE_PIN V13 [get_ports {led[8]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
set_property PACKAGE_PIN V3 [get_ports {led[9]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
set_property PACKAGE_PIN W3 [get_ports {led[10]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
set_property PACKAGE_PIN U3 [get_ports {led[11]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
set_property PACKAGE_PIN P3 [get_ports {led[12]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
set_property PACKAGE_PIN N3 [get_ports {led[13]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
set_property PACKAGE_PIN P1 [get_ports {led[14]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]

# Zero Flag (Top left LED: LED15) 
set_property PACKAGE_PIN L1 [get_ports {led_zero}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led_zero}]